name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repository
      uses: actions/checkout@v4
    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip' # caching pip dependencies
    - name: install packages
      run: pip install ./pynuml ./nugraph
    - name: analysing the code with pylint
      id: pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: running python unit tests
      run: pytest
      