name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: numl.yaml
        miniforge-version: latest
    - name: Analysing the code with pylint
      id: pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Install packages
      run: |
        pip install --no-deps ./pynuml ./nugraph
    - name: Run unit tests
      run: pytest
      