name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setting up the mamba environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: numl
    - name: getting the date
      id: get-date
      run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
      shell: bash
    - name: caching the mamba environment
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ env.CONDA }}/envs
        key:
          conda-${{ runner.os }}--${{ runner.arch }}--${{
          steps.get-date.outputs.today }}-${{
          hashFiles('numl.yml')}}-${{env.CACHE_NUMBER}}
      env:
        CACHE_NUMBER: 0
    - name: updating the mamba environment
      run:
        mamba env update -n numl -f numl.yaml
      if: steps.cache.outputs.cache-hit != 'true'
    - name: analysing the code with pylint
      id: pylint
      run: |
        mamba list
        pylint $(git ls-files '*.py')
    - name: installing local packages
      run: |
        pip install --no-deps ./pynuml ./nugraph
    - name: running python unit tests
      run: pytest
      